In [1]:
import numpy as np
import pandas as pd

In [2]:
np.__version__  

'1.23.4'

Question 1: NumPy's version is 1.23.3.

In [3]:
car_data = pd.read_csv('./data.csv')

car_data.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

Question 2: There are 11914 records in the dataset.

In [4]:
car_data.shape


(11914, 16)

In [5]:
car_data['Make'].value_counts().head(3)

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

Question 3: The most frequent car manufacturers are Chevrolet, Ford and Volkswagen.

In [6]:
car_data.loc[car_data['Make'] == 'Audi', 'Model'].agg(['nunique', 'count', 'size'])

nunique     34
count      328
size       328
Name: Model, dtype: int64

Question 4: 34 unique Audi car models.

In [7]:
car_data.loc[:, car_data.isna().any()].shape

(11914, 5)

Question 5: 5 columns have missing values.

In [8]:
engine_median = car_data['Engine Cylinders'].median()
engine_median

6.0

In [9]:
engine_mode = car_data['Engine Cylinders'].mode()
engine_mode

0    4.0
Name: Engine Cylinders, dtype: float64

In [10]:
car_data['Engine Cylinders'].fillna(engine_mode)

0        6.0
1        6.0
2        6.0
3        6.0
4        6.0
        ... 
11909    6.0
11910    6.0
11911    6.0
11912    6.0
11913    6.0
Name: Engine Cylinders, Length: 11914, dtype: float64

In [11]:
engine_median_updated = engine_median = car_data['Engine Cylinders'].median()
engine_median_updated

6.0

Question 6: No

In [12]:
lotus_data = car_data[car_data['Make'] == 'Lotus']
lotus_data.head()

Make  Model  Year             Engine Fuel Type  Engine HP  \
3912  Lotus  Elise  2009  premium unleaded (required)      189.0   
3913  Lotus  Elise  2009  premium unleaded (required)      218.0   
3914  Lotus  Elise  2009  premium unleaded (required)      189.0   
3915  Lotus  Elise  2010  premium unleaded (required)      189.0   
3916  Lotus  Elise  2010  premium unleaded (required)      218.0   

      Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
3912               4.0            MANUAL  rear wheel drive              2.0   
3913               4.0            MANUAL  rear wheel drive              2.0   
3914               4.0            MANUAL  rear wheel drive              2.0   
3915               4.0            MANUAL  rear wheel drive              2.0   
3916               4.0            MANUAL  rear wheel drive              2.0   

              Market Category Vehicle Size Vehicle Style  highway MPG  \
3912  Exotic,High-Performance      Compact   Convertible           27   
3913  Exotic,High-Performance      Compact   Convertible           26   
3914  Exotic,High-Performance      Compact   Convertible           27   
3915  Exotic,High-Performance      Compact   Convertible           27   
3916  Exotic,High-Performance      Compact   Convertible           26   

      city mpg  Popularity   MSRP  
3912        21         613  43995  
3913        20         613  54990  
3914        21         613  47250  
3915        21         613  47250  
3916        20         613  54990

In [13]:
X = np.array(lotus_data[['Engine HP', 'Engine Cylinders']].drop_duplicates())
print(X)

[[189.   4.]
 [218.   4.]
 [217.   4.]
 [350.   8.]
 [400.   6.]
 [276.   6.]
 [345.   6.]
 [257.   4.]
 [240.   4.]]


In [14]:
XTX = X.T.dot(X)
print(XTX)

[[7.31684e+05 1.34100e+04]
 [1.34100e+04 2.52000e+02]]


In [15]:
XTX_inverse = np.linalg.inv(XTX)
print(XTX_inverse)

[[ 5.53084235e-05 -2.94319825e-03]
 [-2.94319825e-03  1.60588447e-01]]


In [16]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
print(y)

[1100  800  750  850 1300 1000 1000 1300  800]


In [17]:
w = XTX_inverse.dot(X.T).dot(y)
w

array([  4.59494481, -63.56432501])

Question 7: 4.5949